export const ENDPOINTS = {
    AUTH: {
        LOGIN: "/login",
        REGISTER: "/register",
        ME: "/me",
        LOGOUT: "/logout",
    },
    EMPLOYEES: {
        LIST: "/employees",
        DETAILS: (id: string | number) => `/employees/${id}`,
        CREATE: "/employees",
        UPDATE: (id: string | number) => `/employees/${id}`,
        DELETE: (id: string | number) => `/employees/${id}`,
    },
    REFERENCE_DATA: "/reference-data",
    PROGRAMS: {
        LIST: "/temp-contract-projects",
        DETAILS: (id: string | number) => `/temp-contract-projects/${id}`,
        CREATE: "/temp-contract-projects",
        UPDATE: (id: string | number) => `/temp-contract-projects/${id}`,
        DELETE: (id: string | number) => `/temp-contract-projects/${id}`,
    },
    TEMP_CONTRACT_EMPLOYEES: {
        LIST: "/temp-contract-employees",
        DETAILS: (id: string | number) => `/temp-contract-employees/${id}`,
        CREATE: "/temp-contract-employees",
        UPDATE: (id: string | number) => `/temp-contract-employees/${id}`,
        DELETE: (id: string | number) => `/temp-contract-employees/${id}`,
    },
    DOCUMENTS: {
        ACADEMIC: "academic-documents",
        ADMINISTRATIVE: "administrative-documents",
        STATUS: (id: string | number) => `employee-documents/${id}/status`,
        DELETE: (id: string | number) => `employee-documents/${id}`,
        DOWNLOAD: (id: string | number) => `academic-documents/${id}/download`,
    },
    TRAINING_COURSES: {
        LIST: "/training-courses",
        DATA: "/training-courses/data",
        DETAILS: (id: string | number) => `/training-courses/${id}`,
        CREATE: "/training-courses",
        UPDATE: (id: string | number) => `/training-courses/${id}`,
        DELETE: (id: string | number) => `/training-courses/${id}`,
    },
    EMPLOYEE: {
        DASHBOARD: "/employee/dashboard",
        PAYSLIPS: "/employee/payslips",
        PAYSLIP: "/employee/payslip",
        SPOUSES: "/employee/spouses",
        CHILDREN: "/employee/children",
        DEPENDENTS: "/employee/dependents",
        UPDATE_PROFILE_PHOTO: "/employee/profile-photo",
        UPDATE_PASSWORD: "/employee/update-password",
        PROFILE_UPDATE_REQUEST: "/employee/profile-update-request",
        DEGREES: "/employee-degrees",
    },
    ADMIN: {
        PROFILE_UPDATE_REQUESTS: "/admin/profile-update-requests",
        APPROVE_PROFILE_REQUEST: (id: number | string) => `/admin/profile-update-requests/${id}/approve`,
        REJECT_PROFILE_REQUEST: (id: number | string) => `/admin/profile-update-requests/${id}/reject`,
        // Family Approvals
        SPOUSES: "/employees/spouses/data",
        APPROVE_SPOUSE: (id: number | string) => `/employees/spouses/${id}/approve`,
        REJECT_SPOUSE: (id: number | string) => `/employees/spouses/${id}/reject`,
        CHILDREN: "/employees/children/data",
        APPROVE_CHILD: (id: number | string) => `/employees/children/${id}/approve`,
        REJECT_CHILD: (id: number | string) => `/employees/children/${id}/reject`,
        DEPENDENTS: "/employees/dependents/data",
        APPROVE_DEPENDENT: (id: number | string) => `/employees/dependents/${id}/approve`,
        REJECT_DEPENDENT: (id: number | string) => `/employees/dependents/${id}/reject`,
        // Approval Archive
        APPROVAL_ARCHIVE: "/admin/approval-archive",
        APPROVAL_ARCHIVE_EMPLOYEES: "/admin/approval-archive/employees",
        TRAINING_PARTICIPANTS: "/admin/training-participants",
        USERS: {
            LIST: "/admin/users",
            DETAILS: (id: string | number) => `/admin/users/${id}`,
            CREATE: "/admin/users",
            UPDATE: (id: string | number) => `/admin/users/${id}`,
            DELETE: (id: string | number) => `/admin/users/${id}`,
            ROLES_LIST: "/admin/roles-list",
        },
        ROLES: {
            LIST: "/admin/roles",
            DETAILS: (id: string | number) => `/admin/roles/${id}`,
            CREATE: "/admin/roles",
            UPDATE: (id: string | number) => `/admin/roles/${id}`,
            DELETE: (id: string | number) => `/admin/roles/${id}`,
            PERMISSIONS_LIST: "/admin/permissions-list",
        }
    }
} as const;
